language: ruby

os: linux
dist: xenial

jobs:
  fast_finish: true
  include:
  - rvm: 2.5
  - rvm: 2.6
  - rvm: 2.7
  - rvm: ruby-head
  allow_failures:
  - rvm: ruby-head

services:
- postgresql

addons:
  postgresql: 12
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
    - postgresql-server-dev-12
    - postgresql-client-common
    - postgresql-common

env:
  global:
  - PGPORT=5433

cache: bundler

before_install:
- gem install bundler
- sudo cp /etc/postgresql/9.6/main/pg_hba.conf /etc/postgresql/12/main/pg_hba.conf
- sudo service postgresql restart 12
- sleep 1

install: bundle install

before_script:
- psql -c 'create database sequel_plugins;' -U postgres

script:
- bundle exec rspec
- bundle exec rubocop

deploy:
  provider: rubygems
  api_key:
    secure: cwFaLzVdRiYWvNkIAEL+1EduaxdSmuBeJNQ/EikaiUIXyW6FesepZfRTlfFd/hmK3XlcWwm1QVAzPR/RtNASHGhO+52LWInryqdfVeg0xqqijMEYMLipNf5boprgpqL1uh8ADs8jMSWmgtgXXTveHTg9WWrcQ7FYDVJ8QCxKPTeXUIL1O+0YLT2vKoRCD47yoAxu3mz1Ok6dk2Z3RjZVDPqbKrqUnj4EStrppKdWcapG04gq8vzrMVfuu6ek3ijJRsQui9GZNPSoRO3EIoHu9EtmC/s5JTmFQGJZv/xJPVQGmOFLVgXAS7R/id5VDIH9Kv/5jWFYzE7LD3bzUBPZ8GcNSsmjHGuIbdJr87e9m/B+SnAd/SI3hV80Mfq0MJpx8UArcbXPu+oa/oFxoN79hGo8fjMIjRtOBQYmkLr50VvYXUD2Kn7mBEgFWekPPuXbAvL5cHN1PNo1vYJC5PcEeZRow7yx1LS35VAsE0WLAQrnOH1kMc+neFnddDV8v0GXDsqOiWbrJDvDzNH/tjiQcEKhJkab5f7eGRoCLV3SCisijzTyRdzL9ijlrwCo3U1JGkimS+ToTOiWorAOtwxaYLnqKSrIHY0SJ3rVChZtVkOcaHBe1PgW5glD22C1X1fpiuH/jpGrTC986zlyCop7GBoILK+Cz/pNNcoWapglaW0=
  gemspec: umbrellio-sequel-plugins.gemspec
  on:
    repo: umbrellio/umbrellio-sequel-plugins
    branch: master
